### ISSUE TITLE
3.0.2 compile error with chef 12.5.1

### ISSUE THREAD

**Issue by csghuser** [nathwill/chef-systemd#109]
Thank you for creating and maintaining this cookbook. 

Since the systemd cookbook was updated, we are now seeing the following issue with chef 12.5.1:

```      
       Starting Chef Client, version 12.5.1
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/systemd/resources/automount.rb
       ================================================================================

       NameError
       ---------
       uninitialized constant Chef::Resource::SystemdUnit

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/systemd/libraries/resource_factory.rb:59:in `build_resource'
         /tmp/kitchen/cookbooks/systemd/libraries/resource_factory.rb:28:in `included'
         /tmp/kitchen/cookbooks/systemd/resources/automount.rb:5:in `include'
         /tmp/kitchen/cookbooks/systemd/resources/automount.rb:5:in `class_from_file'
         /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:41:in `build_from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/systemd/libraries/resource_factory.rb:

        52:            # Avoid chef-sugar before/after filter conflicts
        53:            # https://github.com/nathwill/chef-systemd/issues/103
        54:            define_method(:before) { |arg| unit_before arg }
        55:            define_method(:after) { |arg| unit_after arg }
        56:  
        57:            default_action :create
        58:  
        59>>           Chef::Resource::SystemdUnit.allowed_actions.each do |actn|
        60:              action actn do
        61:                systemd_unit "#{new_resource.name}.#{resource_type}" do
        62:                  triggers_reload new_resource.triggers_reload
        63:                  user new_resource.user if new_resource.user
        64:                  content property_hash(data)
        65:                  verify new_resource.verify
        66:                  action actn
        67:                end
        68:              end
```
Is this version of chef still supported?

**Comment by nathwill** [comment]
not in version 3 of the cookbook, no. the systemd_unit resource that underpins version 3 didn't make it into chef core until 12.11.
